package:
  name: golem
  version: "1.2.5"
  epoch: 0
  description: "Golem is an open source durable computing platform that makes it easy to build and deploy highly reliable distributed systems."
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - gcc
      - openssl-dev
      - pkgconf
      - protobuf-dev
      - protoc
      - rust
      - rustup
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/golemcloud/golem
      tag: v${{package.version}}
      expected-commit: 5e66ffec498dc4dc58855ae35c0ccfd067221b77

  - name: Configure and build
    runs: |
      export PATH=$PATH:$HOME/.cargo/bin

      cargo install --force cargo-make

      cargo make --profile ci build-release

      mkdir -p ${{targets.contextdir}}/usr/bin/

      mv ./target/release/golem-component-service ${{targets.contextdir}}/usr/bin/golem-component-service

  - uses: strip

subpackages:
  - name: ${{package.name}}-component-service
    dependencies:
      runtime:
        # https://github.com/golemcloud/golem/blob/3649cae14476dd534b6d51d12e686b1f020aa27b/golem-component-service/docker/Dockerfile#L20
        - ca-certificates-bundle
        - openssl
        - libssl3
    pipeline:
      - runs: |
          install -d ${{targets.subpkgdir}}/db/
          install -Dm755 ./target/release/golem-component-service ${{targets.subpkgdir}}/usr/bin/golem-component-service
          ln -sf /usr/bin/golem-component-service ${{targets.subpkgdir}}/golem-component-service

          install -Dm755 ./golem-component-service/config/component-service.toml ${{targets.subpkgdir}}/config/component-service.toml
          cp -R ./golem-component-service/db/* ${{targets.subpkgdir}}/db/
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/ldd-check
        - name: Test symlinks
          runs: |
            set -e
            test "$(readlink /golem-component-service)" = "/usr/bin/golem-component-service"

  - name: ${{package.name}}-component-compilation-service
    dependencies:
      runtime:
        # https://github.com/golemcloud/golem/blob/main/golem-component-compilation-service/docker/Dockerfile#L19
        - ca-certificates-bundle
        - openssl
        - libssl3
    pipeline:
      - runs: |
          install -Dm755 ./target/release/golem-component-compilation-service ${{targets.subpkgdir}}/usr/bin/golem-component-compilation-service
          ln -sf /usr/bin/golem-component-compilation-service ${{targets.subpkgdir}}/golem-component-compilation-service

          install -Dm755 ./golem-component-compilation-service/config/component-compilation-service.sample.env ${{targets.subpkgdir}}/config/component-compilation-service.sample.env
          install -Dm755 ./golem-component-compilation-service/config/component-compilation-service.toml ${{targets.subpkgdir}}/config/component-compilation-service.toml
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/ldd-check
        - name: Test symlinks
          runs: |
            set -e
            test "$(readlink /golem-component-compilation-service)" = "/usr/bin/golem-component-compilation-service"

  - name: ${{package.name}}-shard-manager
    dependencies:
      runtime:
        # https://github.com/golemcloud/golem/blob/main/golem-shard-manager/docker/Dockerfile#L19
        - ca-certificates-bundle
        - openssl
        - libssl3
    pipeline:
      - runs: |
          install -Dm755 ./target/release/golem-shard-manager ${{targets.subpkgdir}}/usr/bin/golem-shard-manager
          ln -sf /usr/bin/golem-shard-manager ${{targets.subpkgdir}}/golem-shard-manager

          install -Dm755 ./golem-shard-manager/config/shard-manager.sample.env ${{targets.subpkgdir}}/config/shard-manager.sample.env
          install -Dm755 ./golem-shard-manager/config/shard-manager.toml ${{targets.subpkgdir}}/config/shard-manager.toml
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/ldd-check
        - name: Test symlinks
          runs: |
            set -e
            test "$(readlink /golem-shard-manager)" = "/usr/bin/golem-shard-manager"

  - name: ${{package.name}}-worker-executor
    dependencies:
      runtime:
        # https://github.com/golemcloud/golem/blob/main/golem-worker-executor/docker/Dockerfile#L19
        - ca-certificates-bundle
        - openssl
        - libssl3
    pipeline:
      - runs: |
          install -Dm755 ./target/release/worker-executor ${{targets.subpkgdir}}/usr/bin/worker-executor
          ln -sf /usr/bin/worker-executor ${{targets.subpkgdir}}/worker-executor

          install -Dm755 ./golem-worker-executor/config/worker-executor.toml ${{targets.subpkgdir}}/config/worker-executor.toml
          install -Dm755 ./golem-worker-executor/config/worker-executor.sample.env ${{targets.subpkgdir}}/config/worker-executor.sample.env
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/ldd-check
        - name: Test symlinks
          runs: |
            set -e
            test "$(readlink /worker-executor)" = "/usr/bin/worker-executor"

  - name: ${{package.name}}-worker-service
    dependencies:
      runtime:
        # https://github.com/golemcloud/golem/blob/main/golem-worker-service/docker/Dockerfile#L20
        - ca-certificates-bundle
        - openssl
        - libssl3
    pipeline:
      - runs: |
          install -d ${{targets.subpkgdir}}/db/

          install -Dm755 ./target/release/golem-worker-service ${{targets.subpkgdir}}/usr/bin/golem-worker-service
          ln -sf /usr/bin/golem-worker-service ${{targets.subpkgdir}}/golem-worker-service

          install -Dm755 ./golem-worker-service/config/worker-service.toml ${{targets.subpkgdir}}/config/worker-service.toml
          install -Dm755 ./golem-worker-service/config/worker-service.sample.env ${{targets.subpkgdir}}/config/worker-service.sample.env

          cp -R ./golem-worker-service/db/* ${{targets.subpkgdir}}/db/
    test:
      environment:
        contents:
          packages:
            - ${{package.name}}
      pipeline:
        - uses: test/tw/ldd-check
        - name: Test symlinks
          runs: |
            set -e
            test "$(readlink /golem-worker-service)" = "/usr/bin/golem-worker-service"

  - name: ${{package.name}}-compat
    description: Upstream image has `/app` entrypoint, set for compatibility
    pipeline:
      - name: Symlink configuration directory
        runs: |
          mkdir -p ${{targets.subpkgdir}}/app

          ln -sf /usr/bin/config ${{targets.subpkgdir}}/app/config
          ln -sf /usr/bin/db ${{targets.subpkgdir}}/app/db

          ln -sf /usr/bin/golem-component-service ${{targets.subpkgdir}}/app/golem-component-service
          ln -sf /usr/bin/golem-component-compilation-service ${{targets.subpkgdir}}/app/golem-component-compilation-service
          ln -sf /usr/bin/golem-shard-manager ${{targets.subpkgdir}}/app/golem-shard-manager
          ln -sf /usr/bin/golem-worker-service ${{targets.subpkgdir}}/app/golem-worker-service
          ln -sf /usr/bin/worker-executor ${{targets.subpkgdir}}/app/worker-executor

update:
  enabled: true
  ignore-regex-patterns:
    - "-dev.*"
  github:
    identifier: golemcloud/golem
    strip-prefix: v

# This is a metapackage for all the golem components, its supposed to be empty:
test:
  pipeline:
    - uses: test/emptypackage
